### ISSUE TITLE
UPSTART 01: Web API Client

### ISSUE THREAD

**Issue by jerry914** [SOA-02/YoutubeAPITest#1]
## Tasks Overview
- **Submit API Library Github Repo URL**: ✅ Completed
- **GitHub Repository Creation**: ✅ Completed
- **Local Project Setup (git init, README.md, push to GitHub)**: ✅ Completed
- **Branch Creation (api-explore)**: ✅ Completed
- **Store Secret Credentials**: ✅ Completed
- **Add Secrets to .gitignore**: ✅ Completed
- **Ruby Script Creation (lib/)**:
  - Fetch resources using `http` gem: ✅ Completed
  - Parse JSON responses: ✅ Completed
  - Save results into YAML file in `spec/fixtures/`: ✅ Completed
  - Add `spec/fixtures/` to `.gitignore`: ✅ Completed
- **Commit and PR to Merge api-explore to Main**: ❌ Completed

## Unresolved Issues
- **Commit and PR to Merge api-explore to Main**

## RuboCop Comments
- **Gemfile**:  Layout/TrailingEmptyLines: Final newline missing.
- **lib/project_info.rb:56:3**: Lint/ShadowedArgument: Argument file_path was shadowed by a local variable before it was used.
  file_path = generate_unique_filename(dir)

## Next Steps
Please create a pull request and solve your RuboCop violation.

**Comment by PoYaSharonLin** [comment]
**Fix: RuboCop violation solved** 

- [X] Gemfile: Layout/TrailingEmptyLines: Final newline missing.

- [X] lib/project_info.rb:56:3: Lint/ShadowedArgument: Argument file_path was shadowed by a local variable before it was used.

file_path = generate_unique_filename(dir) 

<img width="608" alt="{33FC72C6-1483-4E87-816C-9C6AC185DDC6}" src="https://github.com/user-attachments/assets/6ef125c2-5d49-41b9-8604-5f42d7442f25">

<img width="550" alt="{71AD16CC-4F86-44CD-956D-3C2238A4C503}" src="https://github.com/user-attachments/assets/bc4409d3-7692-46e3-a36a-60730bd98510">
