### ISSUE TITLE
Mini-test Testing Error - gateway_youtube_spec.rb 

### ISSUE THREAD

**Issue by PoYaSharonLin** [SOA-02/YoutubeAPITest#13]
# Running:

EE

Finished in 0.000888s, 2252.2523 runs/s, 0.0000 assertions/s.

  1) Error:
Tests Youtube API library::Channel information#test_0001_HAPPY: should recognize channel:
NameError: uninitialized constant Outline::Youtube
    spec/gateway_youtube_spec.rb:26:in `block (3 levels) in <main>'

  2) Error:
Tests Youtube API library::Channel information#test_0002_HAPPY: should get channel title:
NameError: uninitialized constant Outline::Youtube
    spec/gateway_youtube_spec.rb:26:in `block (3 levels) in <main>'

**Comment by PoYaSharonLin** [comment]
**Fifi Test:** 
![image](https://github.com/user-attachments/assets/a69502f8-f1d0-4448-98fb-b1f1cfdf6c10)

error是@channel.find(CHANNEL_ID)

**Comment by PoYaSharonLin** [comment]
Sharon Test Conclusion: 

> 1. gateway_youtube_spec.rb & youtube_api_spec.rb -> Name Error
> 2. Unable to read files in app
<img width="331" alt="{455362EF-6CC9-4199-8689-16B44FDE312B}" src="https://github.com/user-attachments/assets/77a97743-1f8a-4f20-b6c3-418605673e5a">
<img width="662" alt="{99358D18-BA90-4990-A5B6-61DF34552AF0}" src="https://github.com/user-attachments/assets/c413db1a-8021-4e1e-b327-acf034715245">



________________________ FYI________________________

**Step1: ruby -Ilib:test gateway_youtube_spec.rb**
<img width="608" alt="{2CAF47D8-F057-4126-AB56-B084445EF0C0}" src="https://github.com/user-attachments/assets/b64d3b51-f757-420e-90e9-c0189c88bb08">

Action: Check  ruby -Ilib:test youtube_api_spec.rb

Step 2: ruby -Ilib:test youtube_api_spec.rb
<img width="686" alt="{099C8564-CE8C-4262-ABD8-6CE2462F3694}" src="https://github.com/user-attachments/assets/96f64bbd-88f4-4a67-a244-13ea6ad7c5eb">

Action: Check require_app.rb 

Step 3: ruby require_app.rb
root@LAPTOP-8RON5KJV:~/YoutubeAPITest# ruby require_app.rb
require_app defined successfully

Step 4: require ruby spec_helper.rb
<img width="560" alt="{3043DE4B-F9D5-47A4-BE9D-88413412CB05}" src="https://github.com/user-attachments/assets/6d83c541-3367-4ce3-a339-48bded44713c">

Step 5: 
<img width="960" alt="{9607516B-B97D-4852-A0DB-23578EF185AE}" src="https://github.com/user-attachments/assets/00dd53cf-c54c-4de4-beef-f866c28f6f6a">

**Comment by MING-CHUNLee** [comment]
1.Please follow the handout,do not belive the chatpgt everytime😫
2.The path must be returned to the directory before you can enter the folder and read the file.(If you want to print in spec-helper.rb)

**Comment by PoYaSharonLin** [comment]
Hi Mindy 

Message received and problem solved thx to ur help. I‘ll close the issue.
